--Swedbank demo database 

--Person table
CREATE TABLE person (
	pid bigint PRIMARY KEY,
	first_name varchar(255) not null,
	middle_name varchar(255),
	last_name varchar(255) not null,
	email varchar(255),
	phone varchar(255)
);


--Person data
insert into person (pid, first_name, middle_name, last_name, email, phone) values (38202020577,'Testas', '',  'Testauskas', 'test@test.com', '+37060035645' );


--Group table
CREATE TABLE "group" (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(255) not null,
	details varchar(255)
	
);

create sequence group_sequence start with 1 increment by 1;

insert into "group" (name, details) values ('Test Group', 'This is test group');

--Person group relation table
CREATE TABLE person_group (
	pid bigint REFERENCES PERSON(pid),
	group_id BIGINT REFERENCES "group"(id)
);

insert into person_group (pid, group_id) values (38202020577, 1);



--Task table
CREATE TABLE task (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	short_desc varchar(255) not null,
	details text,
	start_date date not null, 
	end_date date 
);

create sequence task_sequence start with 1 increment by 1;

